### ISSUE TITLE
Is it necessary to apply the patch in the kernel 3.16.0-37-generic?

### ISSUE THREAD

**Issue by jpereira** [michael-dev/ebtables-dhcpsnooping#2]
Hi @michael-dev,

Is it necessary to apply the patch in the kernel 3.16.0-37-generic? Because I have checked in the kernel source[1] and they looks like the same behavior added by your patch.

[1] https://github.com/torvalds/linux/blob/v3.16/net/bridge/br_fdb.c

**Comment by michael-dev** [comment]
The referenced upstream code looks good as it has the changes [1]. Thought you might need to check with the actual sources of 3.16.0-37-generic, because this does not look like a vanilla kernel.

[1] http://git.embedian.com/developer/smarc-ti-linux-kernel/commit/c65c7a306610ee7c13669a8f5601b472c19dc6f1
